insert into ponto (descricao)
#Ida
("R. Mira Mangue, 182-372 - Planalto, Natal - RN, 59073-230, Brasil"),
("R. Mira Mangue, 182-372 - Planalto, Natal - RN, 59073-230, Brasil"),
("R. Mira Mangue, 558-734 - Planalto, Natal - RN, 59073-230, Brasil"),
("R. Mira Mangue, 920-1014 - Planalto, Natal - RN, 59073-230, Brasil"),
("R. Mira Mangue, 1106-1224 - Planalto, Natal - RN, 59073-230, Brasil"),
("R. Mira Mangue, 1536-1662 - Planalto, Natal - RN, 59073-230, Brasil"),
("R. Monte Rei, 1-59 - Planalto, Natal - RN, 59073-020, Brasil"),
("R. Serra dos Carajás, 396-778 - Pitimbu, Natal - RN, 59068-200, Brasil"),
("R. Serra dos Carajás, 7978-7980 - Pitimbu, Natal - RN, 59068-200, Brasil"),
("R. Serra dos Carajás, 9984-9986 - Pitimbu, Natal - RN, 59068-200, Brasil"),
("R. Serra dos Carajás, 10016 - Pitimbu, Natal - RN, 59068-200, Brasil"),
("R. das Algarobas, 80-152 - Pitimbu, Natal - RN, 59067-500, Brasil"),
("R. das Algarobas, 230-302 - Pitimbu, Natal - RN, 59067-500, Brasil"),
("R Das Algarobas, 680, Rio Grande Do Norte, Pitimbu (Natal)"),
("R. das Algarobas, 966-1004 - Pitimbu, Natal - RN, 59067-500, Brasil"),
("R. das Algarobas, 1118-1192 - Pitimbu, Natal - RN, 59067-500, Brasil"),
("R Das Algarobas, 1398, Rio Grande Do Norte, Pitimbu (Natal)"),
("R Gameleira, 725, Rio Grande Do Norte, Pitimbu (Natal)"),
("R Do Oiti, 384, Rio Grande Do Norte, Pitimbu (Natal)"),
("R Cidade Do Sol, 2245, Rio Grande Do Norte, Pitimbu (Natal)"),
("Av Sen. Salgado Filho - Pista Lateral, 5648, Rio Grande Do Norte, Pitimbu (Natal)"),
("Av Sen. Salgado Filho, Rio Grande Do Norte, Lagoa Nova (Natal)"),
("Acesso, Rio Grande Do Norte, Neopolis (Natal)"),
("SEM NOME, Rio Grande Do Norte, Capim Macio (Natal)"),
("Av Sen. Salgado Filho - Pista Lateral, 3929, Rio Grande Do Norte, Capim Macio (Natal)"),
("R Sen. Jesse P Freire, 1, Rio Grande Do Norte, Lagoa Nova (Natal)"),
("Av Sen. Salgado Filho - Pista Lateral, 2575, Rio Grande Do Norte, Lagoa Nova (Natal)"),
("Av Prudente De Morais, 5603, Rio Grande Do Norte, Lagoa Nova (Natal)"),
("Av Prudente De Morais, 5119, Rio Grande Do Norte, Lagoa Nova (Natal)"),
("Av Prudente De Morais, 4671, Rio Grande Do Norte, Lagoa Nova (Natal)"),
("Av. Prudente de Morais, 4029-4169 - Lagoa Nova, Natal - RN, 59056-200, Brasil"),
("Av Prudente De Morais, 3517, Rio Grande Do Norte, Barro Vermelho (Natal)"),
("Av Prudente De Morais, 2927, Rio Grande Do Norte, Barro Vermelho (Natal)"),
("Av Prudente De Morais, 2643, Rio Grande Do Norte, Barro Vermelho (Natal)"),
("Av Prudente De Morais, 2331, Rio Grande Do Norte, Barro Vermelho (Natal)"),
("Av Prudente De Morais, 1617, Rio Grande Do Norte, Tirol (Natal)"),
("Av Prudente De Morais, 1269, Rio Grande Do Norte, Tirol (Natal)"),
("Av Prudente De Morais, 1017, Rio Grande Do Norte, Tirol (Natal)"),
("Av Prudente De Morais, 319, Rio Grande Do Norte, Petropolis (Natal)"),
("R Gen. Gustavo De Farias, 477, Rio Grande Do Norte, Petropolis (Natal)"),
("Av Gen. Farias, 681, Rio Grande Do Norte, Ribeira (Natal)"),
("R Almino Affonso, 99, Rio Grande Do Norte, Ribeira (Natal)"),
("R Pereira Simoes, 75, Rio Grande Do Norte, Rocas (Natal)"),
("R Pereira Simoes, 125, Rio Grande Do Norte, Rocas (Natal)"),
("R Do Areial, 340, Rio Grande Do Norte, Rocas (Natal)"),
("R Belo Horizonte, 428, Rio Grande Do Norte, Rocas (Natal)"),
("R Rodrigues Dias, 257, Rio Grande Do Norte, Praia Do Meio (Natal)"),
("R Vinte E Cinco De Dezembro, 123, Rio Grande Do Norte, Praia Do Meio (Natal)"),
("R Do Motor, 611, Rio Grande Do Norte, Praia Do Meio (Natal)"),
("R Do Motor, 671, Rio Grande Do Norte, Praia Do Meio (Natal)"),
("R. Fabrício Pedrosa, 4-16 - Areia Preta, Natal - RN, 59014-030, Brasil"),
("R. Fabrício Pedrosa, 88-98 - Areia Preta, Natal - RN, 59014-030, Brasil"),
("Av. Governador Sílvio Pedroza, 154-226 - Areia Preta, Natal - RN, 59014-100, Brasil"),
("Av. Governador Sílvio Pedroza, 254-270 - Areia Preta, Natal - RN, 59014-100, Brasil"),
("Via Costeira, 428-546 - Mãe Luíza, Natal - RN, 59014-100, Brasil"),
#Volta
("R Joao XxIIi, 1669, Rio Grande Do Norte, Mae Luiza (Natal)"),
("R Joao XxIIi, 1464, Rio Grande Do Norte, Mae Luiza (Natal)"),
("R Joao XxIIi, 1312, Rio Grande Do Norte, Mae Luiza (Natal)"),
("R Joao XxIIi, 1141, Rio Grande Do Norte, Mae Luiza (Natal)"),
("R S. Jose, 13, Rio Grande Do Norte, Mae Luiza (Natal)"),
("R Joao XxIIi, 653, Rio Grande Do Norte, Mae Luiza (Natal)"),
("R Florestal, 157, Rio Grande Do Norte, Mae Luiza (Natal)"),
("R. Des. Benício Filho, 474-504 - Petrópolis, Natal - RN, 59014-470, Brasil"),
("Av Hermes Da Fonseca, 2678, Rio Grande Do Norte, Petropolis (Natal)"),
("R Cel. Joaquim Manoel, 632, Rio Grande Do Norte, Petropolis (Natal)"),
("Av Prudente De Morais, 334, Rio Grande Do Norte, Petropolis (Natal)"),
("Av Prudente De Morais, 686, Rio Grande Do Norte, Tirol (Natal)"),
("Av Prudente De Morais, 1190, Rio Grande Do Norte, Tirol (Natal)"),
("Av Prudente De Morais, 1638, Rio Grande Do Norte, Tirol (Natal)"),
("Av Prudente De Morais, 2136, Rio Grande Do Norte, Barro Vermelho (Natal)"),
("Av Prudente De Morais, 2420, Rio Grande Do Norte, Barro Vermelho (Natal)"),
("Av Prudente De Morais, 2672, Rio Grande Do Norte, Barro Vermelho (Natal)"),
("Av Prudente De Morais, 3010, Rio Grande Do Norte, Barro Vermelho (Natal)"),
("Av Prudente De Morais, 3556, Rio Grande Do Norte, Barro Vermelho (Natal)"),
("Av. Prudente de Morais, 4120-4226 - Lagoa Nova, Natal - RN, 59054-700, Brasil"),
("Av Prudente De Morais, 4570, Rio Grande Do Norte, Lagoa Nova (Natal)"),
("Av Prudente De Morais, 5002, Rio Grande Do Norte, Lagoa Nova (Natal)"),
("Av Prudente De Morais, 5568, Rio Grande Do Norte, Lagoa Nova (Natal)"),
("Av Sen. Salgado Filho - Pista Lateral, 2472, Rio Grande Do Norte, Lagoa Nova (Natal)"),
("Av Sen. Salgado Filho - Pista Lateral, 2954, Rio Grande Do Norte, Candelaria (Natal)"),
("Av Sen. Salgado Filho - Pista Lateral, 3832, Rio Grande Do Norte, Candelaria (Natal)"),
("Av Sen. Salgado Filho, Rio Grande Do Norte, Candelaria (Natal)"),
("Av Sen. Salgado Filho, Rio Grande Do Norte, Candelaria (Natal)"),
("Av Sen. Salgado Filho, Rio Grande Do Norte, Candelaria (Natal)"),
("Av Sen. Salgado Filho, Rio Grande Do Norte, Candelaria (Natal)"),
("Av Sen. Salgado Filho, Rio Grande Do Norte, Candelaria (Natal)"),
("Av Sen. Salgado Filho, Rio Grande Do Norte, Candelaria (Natal)"),
("R Cidade Do Sol, 2477, Rio Grande Do Norte, Pitimbu (Natal)"),
("R Do Oiti, 84, Rio Grande Do Norte, Pitimbu (Natal)"),
("Av Dos Xavantes, 3555, Rio Grande Do Norte, Pitimbu (Natal)"),
("Av Dos Xavantes, 3308, Rio Grande Do Norte, Pitimbu (Natal)"),
("Av Dos Xavantes, 3078, Rio Grande Do Norte, Pitimbu (Natal)"),
("Av Dos Xavantes, 2888, Rio Grande Do Norte, Pitimbu (Natal)"),
("Av Dos Xavantes, 2624, Rio Grande Do Norte, Pitimbu (Natal)"),
("Av Dos Xavantes, 2086, Rio Grande Do Norte, Pitimbu (Natal)"),
("Av Dos Xavantes, 1754, Rio Grande Do Norte, Pitimbu (Natal)"),
("Av Dos Xavantes, 1598, Rio Grande Do Norte, Pitimbu (Natal)"),
("Av Dos Xavantes, 1290, Rio Grande Do Norte, Pitimbu (Natal)"),
("Av Dos Xavantes, 992, Rio Grande Do Norte, Pitimbu (Natal)"),
("Av Dos Xavantes, 714, Rio Grande Do Norte, Pitimbu (Natal)"),
("Av Dos Xavantes, 342, Rio Grande Do Norte, Pitimbu (Natal)"),
("Av Dos Xavantes, 184, Rio Grande Do Norte, Pitimbu (Natal)"),
("R Rio Tamanduatei, 14615, Rio Grande Do Norte, Pitimbu (Natal)"),
("R Serra Da Jurema, 5147, Rio Grande Do Norte, Pitimbu (Natal)"),
("R Monte Rei, 28, Rio Grande Do Norte, Cidade Nova (Natal)"),
("R Mira Mangue, 1585, Rio Grande Do Norte, Planalto (Natal)"),
("R Mira Mangue, 1192, Rio Grande Do Norte, Planalto (Natal)"),
("R Mira Mangue, 950, Rio Grande Do Norte, Planalto (Natal)"),
("R Mira Mangue, 696, Rio Grande Do Norte, Planalto (Natal)"),
("R Mira Mangue, 546, Rio Grande Do Norte, Planalto (Natal)"),
("R Mira Mangue, 410, Rio Grande Do Norte, Planalto (Natal)");
