#Ida
insert into ponto(descricao) values
("R Agrestina, 16740, Rio Grande Do Norte, Planalto (Natal)"),
("R Agrestina, 15548, Rio Grande Do Norte, Planalto (Natal)"),
("R Agrestina, 15104, Rio Grande Do Norte, Planalto (Natal)"),
("R Agrestina, 7970, Rio Grande Do Norte, Planalto (Natal)"),
("R Agrestina, 299, Rio Grande Do Norte, Planalto (Natal)"),
("R Agrestina, 1064, Rio Grande Do Norte, Planalto (Natal)"),
("R Agrestina, 250, Rio Grande Do Norte, Planalto (Natal)"),
("R Agrestina, 57, Rio Grande Do Norte, Planalto (Natal)"),
("R Eng. Joao Helio Alves Rocha, 1984, Rio Grande Do Norte, Planalto (Natal)"),
("R Eng. Joao Helio Alves Rocha, 1696, Rio Grande Do Norte, Planalto (Natal)"),
("R Mira Mangue, 218, Rio Grande Do Norte, Planalto (Natal)"),
("R Mira Mangue, 390, Rio Grande Do Norte, Planalto (Natal)"),
("R Mira Mangue, 634, Rio Grande Do Norte, Planalto (Natal)"),
("R Mira Mangue, 948, Rio Grande Do Norte, Planalto (Natal)"),
("R Mira Mangue, 1208, Rio Grande Do Norte, Planalto (Natal)"),
("R Mira Mangue, 1626, Rio Grande Do Norte, Planalto (Natal)"),
("R Monte Rei, 60, Rio Grande Do Norte, Cidade Nova (Natal)"),
("R Serra Da Jurema, 5345, Rio Grande Do Norte, Pitimbu (Natal)"),
("R Serra Dos Carajas, 522, Rio Grande Do Norte, Pitimbu (Natal)"),
("R Serra Dos Carajas, 2430, Rio Grande Do Norte, Pitimbu (Natal)"),
("R Serra Dos Carajas, 7978, Rio Grande Do Norte, Pitimbu (Natal)"),
("R Serra Dos Carajas, 9984, Rio Grande Do Norte, Pitimbu (Natal)"),
("R Rio Gramame, 4752, Rio Grande Do Norte, Pitimbu (Natal)"),
("R Rio Gramame, 1266, Rio Grande Do Norte, Pitimbu (Natal)"),
("Av Prudente De Morais, 10859, Rio Grande Do Norte, Pitimbu (Natal)"),
("Av Prudente De Morais, 10425, Rio Grande Do Norte, Candelária (Natal)"),
("Av Prudente De Morais, 9815, Rio Grande Do Norte, Candelária (Natal)"),
("Av Prudente De Morais, 9577, Rio Grande Do Norte, Candelária (Natal)"),
("Av Prudente De Morais, 9179, Rio Grande Do Norte, Candelária (Natal)"),
("Av Prudente De Morais, 9059, Rio Grande Do Norte, Candelária (Natal)"),
("Av Prudente De Morais, 8137, Rio Grande Do Norte, Candelária (Natal)"),
("Av Prudente De Morais, 7717, Rio Grande Do Norte, Candelária (Natal)"),
("Av Prudente De Morais, 7491, Rio Grande Do Norte, Candelária (Natal)"),
("R Md Vasconcelos, 127, Rio Grande Do Norte, Candelaria (Natal)"),
("Av Prudente De Morais, 6115, Rio Grande Do Norte, Tirol (Natal)"),
("Av Prudente De Morais, 5609, Rio Grande Do Norte, Lagoa Nova (Natal)"),
("Av Prudente De Morais, 5129, Rio Grande Do Norte, Lagoa Nova (Natal)"),
("Av Prudente De Morais, 4655, Rio Grande Do Norte, Lagoa Nova (Natal)"),
("Av Prudente De Morais, 4117, Rio Grande Do Norte, Tirol (Natal)"),
("R Alberto Silva, 1274, Rio Grande Do Norte, Lagoa Seca (Natal)"),
("R Alberto Silva, 1378, Rio Grande Do Norte, Lagoa Seca (Natal)"),
#Volta
("Av Sen. Salgado Filho, 1174, Rio Grande Do Norte, Lagoa Nova (Natal)"),
("Av Sen. Salgado Filho, 1496, Rio Grande Do Norte, Lagoa Nova (Natal)"),
("Av Sen. Salgado Filho, 1894, Rio Grande Do Norte, Lagoa Nova (Natal)"),
("Av Prudente De Morais, 6156, Rio Grande Do Norte, Lagoa Nova (Natal)"),
("Av Prudente De Morais, 6444, Rio Grande Do Norte, Lagoa Nova (Natal)"),
("Av Prudente De Morais, 7049, Rio Grande Do Norte, Lagoa Nova (Natal)"),
("Av Prudente De Morais, 7325, Rio Grande Do Norte, Lagoa Nova (Natal)"),
("Av Prudente De Morais, 7651, Rio Grande Do Norte, Candelária (Natal)"),
("Av Prudente De Morais, 8059, Rio Grande Do Norte, Candelária (Natal)"),
("Av Prudente De Morais, 9068, Rio Grande Do Norte, Candelária (Natal)"),
("Av Prudente De Morais, 9762, Rio Grande Do Norte, Candelária (Natal)"),
("Av Prudente De Morais, 10378, Rio Grande Do Norte, Candelária (Natal)"),
("Av Dos Xavantes, 1776, Rio Grande Do Norte, Pitimbu (Natal)"),
("Av Dos Xavantes, 1576, Rio Grande Do Norte, Pitimbu (Natal)"),
("Av Dos Xavantes, 1310, Rio Grande Do Norte, Pitimbu (Natal)"),
("Av Dos Xavantes, 990, Rio Grande Do Norte, Pitimbu (Natal)"),
("R Rio Gramare, 5308, Rio Grande Do Norte, Pitimbu (Natal)"),
("Av Dos Xavantes, 356, Rio Grande Do Norte, Pitimbu (Natal)"),
("Av Dos Xavantes, 194, Rio Grande Do Norte, Pitimbu (Natal)"),
("R Rio Tamanduatei, 14731, Rio Grande Do Norte, Pitimbu (Natal)"),
("R Serra Da Jurema, 5173, Rio Grande Do Norte, Pitimbu (Natal)"),
("R Monte Rei, 28, Rio Grande Do Norte, Cidade Nova (Natal)"),
("R Mira Mangue, 1605, Rio Grande Do Norte, Planalto (Natal)"),
("R Mira Mangue, 1234, Rio Grande Do Norte, Planalto (Natal)"),
("R Mira Mangue, 962, Rio Grande Do Norte, Planalto (Natal)"),
("R Mira Mangue, 704, Rio Grande Do Norte, Planalto (Natal)"),
("R Mira Mangue, 542, Rio Grande Do Norte, Planalto (Natal)"),
("R Mira Mangue, 406, Rio Grande Do Norte, Planalto (Natal)"),
("R Mira Mangue, 216, Rio Grande Do Norte, Planalto (Natal)"),
("R Eng. Joao Helio Alves Rocha, 1587, Rio Grande Do Norte, Planalto (Natal)"),
("R Eng. Joao Helio Alves Rocha, 1698, Rio Grande Do Norte, Planalto (Natal)"),
("R Eng. Joao Helio Alves Rocha, 1990, Rio Grande Do Norte, Planalto (Natal)"),
("R Eng. Joao Helio Alves Rocha, 2264, Rio Grande Do Norte, Planalto (Natal)"),
("R Agrestina, 69, Rio Grande Do Norte, Planalto (Natal)"),
("R Agrestina, 250, Rio Grande Do Norte, Planalto (Natal)"),
("R Agrestina, 137, Rio Grande Do Norte, Planalto (Natal)"),
("R Agrestina, 285, Rio Grande Do Norte, Planalto (Natal)"),
("R Agrestina, 15054, Rio Grande Do Norte, Planalto (Natal)"),
("R Agrestina, 15514, Rio Grande Do Norte, Planalto (Natal)"),
("R Agrestina, 16236, Rio Grande Do Norte, Planalto (Natal)"),
("R Agrestina, 16696, Rio Grande Do Norte, Planalto (Natal)"),
("R S. Gregorio, 501, Rio Grande Do Norte, Planalto (Natal)");